name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    if: "contains(github.event.head_commit.message, '[build]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build
        run: |
          mkdir build
          echo "artisandigital.xyz" > build/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: nif.artisandigital.xyz
  
